
name: merge translate

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 拉取仓库代码
    
    - name: Set up JDK 21 # 配置 JDK 版本
      uses: actions/setup-java@v4 
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'pom.xml'

    - name: Compile with Maven # 编译项目
      run: mvn compile

    - name: Copy dependencies # 复制依赖
      run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency

    - name: Run Specified Java Class # 执行
      run: java -cp "target/classes:target/dependency/*" cn.citizenwiki.MergeAndConvert  # 运行指定类
      env:
        PZ_TOKEN: ${{ secrets.AUTHORIZATION }}
        PZ_PROJECT_ID: 8340

    - name: Upload INI files # 上传文件,在action页面可以下载
      uses: actions/upload-artifact@v4
      with:
        name: ini-files
        path: final_output/*.ini
