
name: merge translate

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 拉取仓库代码
    
    - name: Set up JDK 21 # 配置 JDK 版本
      uses: actions/setup-java@v4 
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'pom.xml'

    - name: Compile with Maven
      run: mvn compile

    - name: Copy dependencies
      run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency

    - name: Run Specified Java Class
      run: java -cp "target/classes:target/dependency/*" cn.citizenwiki.MergeAndConvert  # 运行指定类
